
export const products = [
  {
    id: 1,
    title: "Men Casual Shirt",
    brand: "CLAFOUTIS",
    price: 1450,
    oldPrice: 1650,
    discount: 10,
    description: "High quality casual shirt, perfect for everyday wear. Soft, durable, and stylish.",
    rating: 4,         // 0 to 5
    reviews: 24,
    shippingEstimate: "5-7", // working days
    img1: "/fgL13.jpg",
    img2: "/fg13.jpg",
    img3: "/fgL15.jpg",
    category: "Fashion",
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 2,
    title: "Kashee",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fgh1.jpg",
    img2: "/fgL1.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    reviews: 12,
    shippingEstimate: "5-7",
    description: "Trendy Kashee outfit, premium fabric, perfect for casual and semi-formal occasions.",
    
    inStock: true,
    featured: true,
    popular: false
  },
   {
    id: 3,
    title: "UBLP",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fg22.jpg",
    img2: "/fgL22.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    description: "High quality casual shirt, perfect for everyday wear. Soft, durable, and stylish.",
    inStock: false,
    featured: true,
    popular: false
  },
   {
    id: 4,
    title: "kashee",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fg22.jpg",
    img2: "/fgL22.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    description: "High quality casual shirt, perfect for everyday wear. Soft, durable, and stylish.",
    inStock: false,
    featured: false,
    popular: true
  },
   {
    id: 5,
    title: "kashee",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fg22.jpg",
    img2: "/fgL22.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    description: "High quality casual shirt, perfect for everyday wear. Soft, durable, and stylish.",
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 6,
    title: "kashee",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fg22.jpg",
    img2: "/fgL22.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 7,
    title: "kashee",
    brand: "CLAFOUTIS",
    category: "Fashion",
    img1: "/fg22.jpg",
    img2: "/fgL22.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 5,
    inStock: true,
    featured: false,
    popular: true
  },




  {
    id: 8,
    title: "laptop",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "Laptops",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: false,
    popular: true
  },
  {
    id: 9,
    title: "phone",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "phone",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 10,
    title: "Watch",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "phone",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 11,
    title: "SmartGadgets",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "SmartGadgets",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 12,
    title: "Intel",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "laptop",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 13,
    title: "Headphones",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "SmartGadgets",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: false,
    featured: false,
    popular: true
  },
  {
    id: 14,
    title: "Watch",
    brand: "CLAFOUTIS",
    category: "Electronics",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: false,
    popular: true
  },

  {
    id: 15,
    title: "Coach",
    brand: "CLAFOUTIS",
    category: "Bags",
    img1: "/BG1.jpg",
    img2: "/BG2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: true,
    popular: true
  },
   {
    id: 16,
    title: "Coach",
    brand: "CLAFOUTIS",
    category: "Bags",
    img1: "/BG1.jpg",
    img2: "/BG2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 17,
    title: "Coach",
    brand: "CLAFOUTIS",
    category: "Bags",
    img1: "/BG1.jpg",
    img2: "/BG2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 18,
    title: "Coach",
    brand: "CLAFOUTIS",
    category: "Bags",
    img1: "/BG1.jpg",
    img2: "/BG2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true
  },
  
  {
    id: 19,
    title: "Men Running Shoes",
    brand: "CLAFOUTIS",
    category: "Footwear",
    subcategory: "Men",
    img1: "/FS1.jpg",
    img2: "/FS2.jpg",
    price: 1800,
    oldPrice: 4000,
    discount: 30,
    rating: 4,
    inStock: true,
    featured: true,
    popular: true
  },
   {
    id: 20,
    title: "Men Running Shoes",
    brand: "CLAFOUTIS",
    category: "Footwear",
    subcategory: "Men",
    img1: "/FS1.jpg",
    img2: "/FS2.jpg",
    price: 1800,
    oldPrice: 4000,
    discount: 30,
    rating: 4,
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 21,
    title: "Women Running Shoes",
    brand: "CLAFOUTIS",
    category: "Footwear",
    subcategory: "Women",
    img1: "/FS1.jpg",
    img2: "/FS2.jpg",
    price: 1800,
    oldPrice: 4000,
    discount: 30,
    rating: 4,
    inStock: true,
    featured: false,
    popular: true
  },
   {
    id: 22,
    title: "Women Running Shoes",
    brand: "CLAFOUTIS",
    category: "Footwear",
    subcategory: "Women",
    img1: "/FS1.jpg",
    img2: "/FS2.jpg",
    price: 1800,
    oldPrice: 4000,
    discount: 30,
    rating: 4,
    inStock: true,
    featured: false,
    popular: true
  },


  {
    id: 23,
    title: "Lays",
    brand: "CLAFOUTIS",
    category: "Groceries",
    img1: "/LY1.jpg",
    img2: "/LY2.jpg",
    price: 500,
    oldPrice: 200,
    discount: 25,
    rating: 5,
    inStock: true,
    featured: false,
    popular: false
  },
  
  {
    id: 24,
    title: "Lays",
    brand: "CLAFOUTIS",
    category: "Groceries",
    img1: "/LY1.jpg",
    img2: "/LY2.jpg",
    price: 500,
    oldPrice: 200,
    discount: 25,
    rating: 5,
    inStock: true,
    featured: false,
    popular: false
  },
  
  {
    id: 25,
    title: "Lays",
    brand: "CLAFOUTIS",
    category: "Groceries",
    img1: "/LY1.jpg",
    img2: "/LY2.jpg",
    price: 500,
    oldPrice: 200,
    discount: 25,
    rating: 5,
    inStock: true,
    featured: false,
    popular: false
  },
  
  {
    id: 26,
    title: "Lays",
    brand: "CLAFOUTIS",
    category: "Groceries",
    img1: "/LY1.jpg",
    img2: "/LY2.jpg",
    price: 500,
    oldPrice: 200,
    discount: 25,
    rating: 5,
    inStock: true,
    featured: false,
    popular: false
  },


  {
    id: 27,
    title: "Vaseline",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/V1.jpg",
    img2: "/V2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: true,
    popular: true
    
  },
   {
    id: 28,
    title: "Vaseline",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/V1.jpg",
    img2: "/V2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: true,
    popular: true
    
  },
   {
    id: 29,
    title: "Vaseline",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/V1.jpg",
    img2: "/V2.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true
  },



  {
    id: 30,
    title: "Vitamin-C",
    brand: "CLAFOUTIS",
    category: "Accessories",
    img1: "/WM1.jpg",
    img2: "/WM2.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 3,
    inStock: true,
    featured: false,
    popular: false
  },
   {
    id: 31,
    title: "Vitamin-C",
    brand: "CLAFOUTIS",
    category: "Accessories",
    img1: "/WM1.jpg",
    img2: "/WM2.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 3,
    inStock: true,
    featured: true,
    popular: true
  },
   {
    id: 32,
    title: "Vitamin-C",
    brand: "CLAFOUTIS",
    category: "Accessories",
    img1: "/WM1.jpg",
    img2: "/WM2.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 3,
    inStock: true,
    featured: false,
    popular: false
  },
   {
    id: 33,
    title: "Hair-Pins",
    brand: "CLAFOUTIS",
    category: "Accessories",
    img1: "/WM1.jpg",
    img2: "/WM2.jpg",
    price: 2800,
    oldPrice: 4000,
    discount: 30,
    rating: 3,
    inStock: true,
    featured: true,
    popular: true
  },



  {
    id: 34,
    title: "Tesoro",
    brand: "CLAFOUTIS",
    category: "Jewellery",
    img1: "/JR.jpg",
    img2: "/JR1.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 2,
    inStock: true,
    featured: true,
    popular: true
  },
   {
    id: 35,
    title: "Tesoro",
    brand: "CLAFOUTIS",
    category: "Jewellery",
    img1: "/JR.jpg",
    img2: "/JR1.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 2,
    inStock: true,
    featured: true,
    popular: true
  },
   {
    id: 36,
    title: "Tesoro",
    brand: "CLAFOUTIS",
    category: "Jewellery",
    img1: "/JR.jpg",
    img2: "/JR1.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 2,
    inStock: true,
    featured: false,
    popular: false
  },
   {
    id: 37,
    title: "Tesco",
    brand: "CLAFOUTIS",
    category: "Jewellery",
    img1: "/JR.jpg",
    img2: "/JR1.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 2,
    inStock: true,
    featured: false,
    popular: false
  },
   {
    id: 38,
    title: "Tesco",
    brand: "CLAFOUTIS",
    category: "Jewellery",
    img1: "/JR.jpg",
    img2: "/JR1.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 2,
    inStock: true,
    featured: false,
    popular: false
  },

  {
  id: 39,
  title: "Men T-shirt",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Men",       // <-- Men, Women, Kids
  subSubcategory: "T-Shirts", // <-- T-shirts, Jeans, etc
  img1: "/fg22.jpg",
  img2: "/fgL22.jpg",
  price: 2800,
  oldPrice: 4000,
  discount: 30,
  rating: 5,
  inStock: true,
    featured: false,
    popular: false
},
{
  id: 40,
  title: "Women Dress",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Women",
  subSubcategory: "Dresses",
  img1: "/fg24.jpg",
  img2: "/fgL24.jpg",
  price: 3500,
  oldPrice: 5000,
  discount: 25,
  rating: 5,
  inStock: true,
    featured: false,
    popular: false
},
{
  id: 41,
  title: "Kids T-shirt",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Kids",
  subSubcategory: "T-Shirts",
  img1: "/fg25.jpg",
  img2: "/fgL25.jpg",
  price: 1500,
  oldPrice: 2500,
  discount: 15,
  rating: 4,
  inStock: true,
    featured: false,
    popular: false
},
  {
  id: 42,
  title: "Men T-shirt",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Men",       // <-- Men, Women, Kids
 
  img1: "/fg22.jpg",
  img2: "/fgL22.jpg",
  price: 2800,
  oldPrice: 4000,
  discount: 30,
  rating: 5,
  inStock: true,
    featured: false,
    popular: false
},
// Furniture Example
  {
    id: 44,
    title: "King Size Bed",
    brand: "IKEA",
    price: 200,
    oldPrice: 300,
    discount: 33,
    description: "Comfortable king size bed with premium wood finish.",
    rating: 4,
    reviews: 12,
    shippingEstimate: "7-10",
    img1: "/FR1.jpg",
    img2: "/FR1b.jpg",
    img3: "/FR1c.jpg",
    category: "Furniture",
    subcategory: "Bedroom",
    inStock: true,
    featured: true,
    popular: true
  },
  {
    id: 45,
    title: "Leather Sofa",
    brand: "HomeTown",
    price: 350,
    oldPrice: 500,
    discount: 30,
    description: "Premium leather sofa, perfect for living room.",
    rating: 5,
    reviews: 8,
    shippingEstimate: "7-10",
    img1: "/FR2.jpg",
    img2: "/FR2b.jpg",
    img3: "/FR2c.jpg",
    category: "Furniture",
    subcategory: "LivingRoom",
    inStock: true,
    featured: true,
    popular: true
  },

  // Perfumes Example
  {
    id: 46,
    title: "Miss Dior",
    brand: "Dior",
    price: 120,
    oldPrice: 150,
    discount: 20,
    description: "Fragrance for women, elegant and long-lasting.",
    rating: 5,
    reviews: 10,
    shippingEstimate: "3-5",
    img1: "/P1.jpg",
    img2: "/P1b.jpg",
    img3: "/P1c.jpg",
    category: "Perfumes",
    subcategory: null,
    inStock: true,
    featured: true,
    popular: true// optional, perfumes may not need subcategory
  },
    {
    id: 47,
    title: "Miss Gucci",
    brand: "Gucci",
    price: 120,
    oldPrice: 150,
    discount: 20,
    description: "Fragrance for women, elegant and long-lasting.",
    rating: 5,
    reviews: 10,
    shippingEstimate: "3-5",
    img1: "/P1.jpg",
    img2: "/P1b.jpg",
    img3: "/P1c.jpg",
    category: "Perfumes",
    subcategory: null,
    inStock: true,
    featured: true,
    popular: true// optional, perfumes may not need subcategory
  },
  {
    id: 48,
    title: "Britney Spears",
    brand: "Britney",
    price: 1250,
    oldPrice: 1500,
    discount: 15,
    description: "Fragrance for women, elegant and long-lasting.",
    rating: 5,
    reviews: 10,
    shippingEstimate: "3-5",
    img1: "/P1.jpg",
    img2: "/P1b.jpg",
    img3: "/P1c.jpg",
    category: "Perfumes",
    subcategory: null,
    inStock: true,
    featured: true,
    popular: true// optional, perfumes may not need subcategory
  },
  {
  id: 49,
  title: "Women Dress",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Women",
  subSubcategory: "Tops&Tees",
  img1: "/fg24.jpg",
  img2: "/fgL24.jpg",
  price: 3500,
  oldPrice: 5000,
  discount: 25,
  rating: 5,
  inStock: true,
    featured: true,
    popular: true
},
 {
  id: 50,
  title: "Girl Dress",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Kids",
  subSubcategory: "Girls-Clothing",
  img1: "/fg24.jpg",
  img2: "/fgL24.jpg",
  price: 3500,
  oldPrice: 5000,
  discount: 25,
  rating: 5,
  inStock: true,
    featured: false,
    popular: false
},
 {
  id: 51,
  title: "Boy Dress",
  brand: "CLAFOUTIS",
  category: "Fashion",
  subcategory: "Kids",
  subSubcategory: "Boys-Clothing",
  img1: "/fg24.jpg",
  img2: "/fgL24.jpg",
  price: 3500,
  oldPrice: 5000,
  discount: 25,
  rating: 5,
  inStock: true,
    featured: false,
    popular: false
},
{
    id: 52,
    title: "Xbox-Controller",
    brand: "CLAFOUTIS",
    category: "Electronics",
    subcategory: "SmartGadgets",
    img1: "/WW1.jpg",
    img2: "/WW2.jpg",
    price: 1500,
    oldPrice: 2000,
    discount: 25,
    rating: 4,
    inStock: true,
    featured: false,
    popular: false
  },
  {
    id: 53,
    title: "Cosmetic",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/CC.jpg",
    img2: "/CC1.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true,
    
  },
  {
    id: 54,
    title: "Cosmetic",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/CC.jpg",
    img2: "/CC1.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true,
    
  },
  {
    id: 55,
    title: "Cosmetic",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/CC.jpg",
    img2: "/CC1.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true,
    
  },
  {
    id: 56,
    title: "Cosmetic",
    brand: "CLAFOUTIS",
    category: "Beauty",
    img1: "/CC.jpg",
    img2: "/CC1.jpg",
    price: 3200,
    oldPrice: 4500,
    discount: 20,
    rating: 3,
    inStock: true,
    featured: false,
    popular: true,
    
  },
  
];




